version: '3.4'

services:
  fivem:
    image: lionear/fivem
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fivem
    restart: unless_stopped
    stdin_open: true
    tty: true
    volumes:
      - "/path/to/resources:/config"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      LICENSE_KEY: "paste-license-key-here"
